---
multicolumn: false
export-width: 
web-width: 500px
align: center
float: h!
export-filename: 
version: 1
path: figures/Cписок войн без точной геопривязки, но c указанием coordinate location/config.yml
