---
multicolumn: false
export-width: 
web-width: 800
align: center
float: h!
export-filename: 
version: 1
path: figures/Cписок битв без точной геопривязки, но c указанием coordinate location1/config.yml
